keyspace:
  name: userdb
  replicas: 3
  availabilityZones:
    - name: us-east-1a
      replicas: 1
    - name: us-east-1b
      replicas: 1
    - name: us-east-1c
      replicas: 1

  backup:
    schedule: "0 3 * * 1"  # Custom backup schedule for userdb (3 AM every Monday)

vttablet:
  resources:
    limits:
      memory: 4096Mi
      cpu: 4000m
    requests:
      memory: 2048Mi
      cpu: 2000m
