apiVersion: v1
kind: Service
metadata:
  name: {{ include "vitess.fullname" . }}-{{ .Values.component }}
  labels:
    {{- include "vitess.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 15001  # VTGate MySQL port
      targetPort: 15001
      name: mysql
    - port: 15999  # VTctld API port
      targetPort: 15999
      name: vtctld
    - port: 15100  # VTTablet gRPC port
      targetPort: 15100
      name: grpc
  selector:
    app: {{ include "vitess.fullname" . }}-{{ .Values.component }}
